/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserBookRouteImport } from './routes/user/book'
import { Route as UserAuthorRouteImport } from './routes/user/author'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserBookRoute = UserBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => UserRoute,
} as any)
const UserAuthorRoute = UserAuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => UserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserRouteWithChildren
  '/user/author': typeof UserAuthorRoute
  '/user/book': typeof UserBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserRouteWithChildren
  '/user/author': typeof UserAuthorRoute
  '/user/book': typeof UserBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserRouteWithChildren
  '/user/author': typeof UserAuthorRoute
  '/user/book': typeof UserBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/user'
    | '/user/author'
    | '/user/book'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/user' | '/user/author' | '/user/book'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/user'
    | '/user/author'
    | '/user/book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/book': {
      id: '/user/book'
      path: '/book'
      fullPath: '/user/book'
      preLoaderRoute: typeof UserBookRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/author': {
      id: '/user/author'
      path: '/author'
      fullPath: '/user/author'
      preLoaderRoute: typeof UserAuthorRouteImport
      parentRoute: typeof UserRoute
    }
  }
}

interface UserRouteChildren {
  UserAuthorRoute: typeof UserAuthorRoute
  UserBookRoute: typeof UserBookRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserAuthorRoute: UserAuthorRoute,
  UserBookRoute: UserBookRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
