/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as UserBooksIndexRouteImport } from './routes/user/books/index'
import { Route as UserAuthorsIndexRouteImport } from './routes/user/authors/index'
import { Route as UserBooksIdRouteImport } from './routes/user/books/$id'
import { Route as UserAuthorsIdRouteImport } from './routes/user/authors/$id'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const UserBooksIndexRoute = UserBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => UserRoute,
} as any)
const UserAuthorsIndexRoute = UserAuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => UserRoute,
} as any)
const UserBooksIdRoute = UserBooksIdRouteImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => UserRoute,
} as any)
const UserAuthorsIdRoute = UserAuthorsIdRouteImport.update({
  id: '/authors/$id',
  path: '/authors/$id',
  getParentRoute: () => UserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user': typeof UserRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/user/': typeof UserIndexRoute
  '/user/authors/$id': typeof UserAuthorsIdRoute
  '/user/books/$id': typeof UserBooksIdRoute
  '/user/authors/': typeof UserAuthorsIndexRoute
  '/user/books/': typeof UserBooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/user': typeof UserIndexRoute
  '/user/authors/$id': typeof UserAuthorsIdRoute
  '/user/books/$id': typeof UserBooksIdRoute
  '/user/authors': typeof UserAuthorsIndexRoute
  '/user/books': typeof UserBooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/user/': typeof UserIndexRoute
  '/user/authors/$id': typeof UserAuthorsIdRoute
  '/user/books/$id': typeof UserBooksIdRoute
  '/user/authors/': typeof UserAuthorsIndexRoute
  '/user/books/': typeof UserBooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user'
    | '/login'
    | '/signup'
    | '/user/'
    | '/user/authors/$id'
    | '/user/books/$id'
    | '/user/authors/'
    | '/user/books/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/user'
    | '/user/authors/$id'
    | '/user/books/$id'
    | '/user/authors'
    | '/user/books'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/user'
    | '/_auth/login'
    | '/_auth/signup'
    | '/user/'
    | '/user/authors/$id'
    | '/user/books/$id'
    | '/user/authors/'
    | '/user/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/user/books/': {
      id: '/user/books/'
      path: '/books'
      fullPath: '/user/books/'
      preLoaderRoute: typeof UserBooksIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/authors/': {
      id: '/user/authors/'
      path: '/authors'
      fullPath: '/user/authors/'
      preLoaderRoute: typeof UserAuthorsIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/books/$id': {
      id: '/user/books/$id'
      path: '/books/$id'
      fullPath: '/user/books/$id'
      preLoaderRoute: typeof UserBooksIdRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/authors/$id': {
      id: '/user/authors/$id'
      path: '/authors/$id'
      fullPath: '/user/authors/$id'
      preLoaderRoute: typeof UserAuthorsIdRouteImport
      parentRoute: typeof UserRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UserRouteChildren {
  UserIndexRoute: typeof UserIndexRoute
  UserAuthorsIdRoute: typeof UserAuthorsIdRoute
  UserBooksIdRoute: typeof UserBooksIdRoute
  UserAuthorsIndexRoute: typeof UserAuthorsIndexRoute
  UserBooksIndexRoute: typeof UserBooksIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserIndexRoute: UserIndexRoute,
  UserAuthorsIdRoute: UserAuthorsIdRoute,
  UserBooksIdRoute: UserBooksIdRoute,
  UserAuthorsIndexRoute: UserAuthorsIndexRoute,
  UserBooksIndexRoute: UserBooksIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
