INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.import_export",
    "cloudinary",
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # "crispy_forms",
    # "crispy_tailwind",
    "django_extensions",
    "drf_redesign",
    "rest_framework",
    "django_filters",
    "library",
    "import_export",
    "drf_spectacular"
]  # Application definition
