[project]
name = "djangoadmin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cloudinary>=1.45.0",
    # "dj-rest-auth>=7.2.0",
    "django>=6.0.7",
    # "django-allauth>=65.18.0",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.14.0",
    "django-extensions>=4.1",
    "django-filter>=26.1.0",
    "django-import-export>=4.4.1",
    "django-unfold>=0.101.0",
    "djangorestframework>=3.17.1",
    # "djangorestframework-simplejwt>=5.5.1",
    "drf-redesign>=0.6.0",
    "drf-spectacular>=0.30.0",
    "markdown>=3.10.2",
    "pillow>=12.3.0",
    "uvicorn>=0.51.0",
    "whitenoise>=6.12.0",
]
[tool.autopep8]
indent_size = 2
[tool.mypy]
plugins = ["mypy_django_plugin.main"]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "Admin.settings"